format = """
$time\
$sudo\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$python\
$cmd_duration\
$container\
$fill\
$line_break\
${custom.full_git_status}\
$character\
"""

[time]
format = "[$time]($style) "
use_12hr = true
disabled = false

[sudo]
format = "sudo "
disabled = false

[directory]
truncation_length = 10
truncate_to_repo = false
truncation_symbol = ".../"

[cmd_duration]
min_time = 0
format = "[$duration]($style) "
show_notifications = true

[container]
format = "in container: [$name]($style) "

[git_branch]
format = "[$branch(:$remote_branch)]($style) "

[git_commit]
format = "commit: [($hash$tag)]($style) "
tag_disabled = false

[git_status]
format = "([$all_status$ahead_behind]($style)) "
conflicted = "conflict-"
stashed = "stashed-"
deleted = "deleted-"
renamed = "renamed-"
modified = "modified-"
staged = "staged-"
untracked = "untracked-"
diverged = "diverged"
ahead = "ahead"
behind = "behind"
up_to_date = "up_to_date"

[python]
format = "pyvenv: [$virtualenv]($style) "

[fill]
symbol = "-"

[custom.full_git_status]
command = """
git status | (
  if [ $(git status | wc -l) -gt 10 ]; then
    (head -n 9; echo "...")
  else
    cat
  fi
)
"""
when = "[[ -n $(git status 2>/dev/null) ]]"
format = "$output\n"
